# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Chuanfu Chen | OnePhysicist"
title_separator          : "-"
name                     : &name "Chuanfu Chen"
description              : &description "Chuanfu Chen's academic portfolio and research profile"
url                      : "https://OnePhysicist.github.io"
baseurl                  : ""
repository               : "OnePhysicist/OnePhysicist.github.io"

# Site Author - sidebar information
author:
  avatar           : "profile.jpg"   # 你放在 /images/ 下的头像文件
  name             : "陈川福 (Chuanfu Chen)"
  pronouns         : "he/him"
  bio              : "Atmospheric & Climate Scientist | PhD in Mathematical Physics (MSU) | GNSS & Ionosphere"
  location         : "Moscow · Harbin · Shenzhen"
  employer         : "Moscow State University / Harbin Institute of Technology"
  email            : "chuanfu.chen@physics.msu.ru"

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid            : "https://orcid.org/0000-0002-9896-5841"
  researchgate     : "https://www.researchgate.net/profile/Chuanfu-Chen"
  scopus           : # 你可以填上 Scopus ID 链接
  arxiv            : # 如果有 arXiv 作者主页可以加

  # Repositories
  github           : "OnePhysicist"

  # Social media
  linkedin         : # 如果你有 LinkedIn，可填
  twitter          : # 如果要用 X (Twitter)，填用户名
  zhihu            : # 如果想展示知乎，填用户名
  weibo            : # 微博用户名

# Publication categories
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# Site Settings
teaser                   : "profile.jpg"
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"

# Analytics (可选，如果你有 Google Analytics ID，可以在此填入)
analytics:
  provider               : "false"

# Output & timezone
timezone: Asia/Shanghai

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji